### ISSUE TITLE
/availability endpoint does not report when service proxy cert has expired

### ISSUE THREAD

**Issue by zombiepig01** [opencadc/tap#148]
When the cadcproxy cert in the /config directory is expired, the /availability endpoint still reports that the service is up and available.  The /tables endpoint reports an error.  e.g.
```
$ curl https://ws-cadc.canfar.net/youcat/availability
<?xml version="1.0" encoding="UTF-8"?>
<vosi:availability xmlns:vosi="http://www.ivoa.net/xml/VOSIAvailability/v1.0">
  <vosi:available>true</vosi:available>
  <vosi:note>service is accepting queries</vosi:note>
  <!--<clientip>x.x.x.x</clientip>-->
</vosi:availability>

$ curl https://ws-cadc.canfar.net/youcat/tables?detail=min
unexpected exception: java.lang.RuntimeException: CONFIG: servops certificate is invalid
```

**Comment by pdowler** [comment]
fixed in images.opencadc.org/core/youcat:0.6.0

also note that cadc-tap-tmp.properties needs extra config because youcat uses the DelegatingStorageManager - I slipped that into a patch since this image is new and
