### ISSUE TITLE
Queries to escape underscores

### ISSUE THREAD

**Issue by at88mph** [opencadc/tap#16]
This is running with Postgres 9.x and version 1.0.2 of the ```cadc-tap-service```.

Consider this ADQL running on the CADC TAP service:
```sql
SELECT Plane.*
FROM caom2.Plane AS Plane 
	JOIN caom2.Observation AS Observation ON Plane.obsID = Observation.obsID 
WHERE  ( lower(Observation.observationID) LIKE '%123_%' )
```

This query will return everything containing the text ```123```, rather than searching for ```123_``` as requested.  The underscore needs to be escaped as it has special meaning.

**Comment by pdowler** [comment]
Since underscore wildcard behavioru is part of ADQL, the query writer has to decide to escape it or not.
