### ISSUE TITLE
Incorrect number of rows for aggregate queries with the cadc-tap-server-oracle

### ISSUE THREAD

**Issue by andamian** [opencadc/tap#57]
Problem noticed with the ALMA tap. The following query instead of returning 10 rows, it limits to sum(count(*)) = 10

`curl -L -d "QUERY=SELECT top 10 obs_id, count(*) AS observationID from alma.obscore where t_min>1111 group by obs_id&LANG=ADQL" https://almascience.nrao.edu/tap/sync`

It might have to do with inappropriate translation of TOP into Oracle

**Comment by andamian** [comment]
I think the current implementation uses the wrong Oracle keyword to limit the number of rows in the result. It should use FETCH instead:

http://www.oracletutorial.com/oracle-basics/oracle-fetch/

**Comment by at88mph** [comment]
The `FETCH` keyword was added as part of Oracle 12_c_, unfortunately.  ALMA uses Oracle 11.

**Comment by at88mph** [comment]
The fix will (hopefully) be to encompass the original query inside a `FROM` `SUBSELECT`:

```sql
SELECT TOP 10 A, COUNT(*) C FROM T WHERE F() = 5
```
will become
```sql
SELECT A, C FROM (SEELCT A, COUNT(*) C FROM T WHERE F() = 5) WHERE ROWNUM <= 10
```
