### ISSUE TITLE
Remove too specific class for column replacement.

### ISSUE THREAD

**Issue by at88mph** [opencadc/tap#84]
Given this ADQL, the `S_REGION` column should be replaced in the SQL with the `FOOTPRINT` column:

```sql
SELECT TOP 1 S_REGION FROM ivoa.obscore;
```

SQL Query is then:
```sql
SELECT FOOTPRINT FROM (SELECT FOOTPRINT FROM ivoa.obscore)
WHERE ROWNUM <= 1
```

However, if the `S_REGION` is mixed or lowercase, it does not get replaced:
```sql
SELECT TOP 1 s_region FROM ivoa.obscore;
```
```sql
SELECT s_region FROM (SELECT s_region FROM ivoa.obscore)
WHERE ROWNUM <= 1
```

Which will often fail trying to convert the Oracle `SDO_GEOMETRY` objects back into DALI strings.  It's a simple `equalsIgnoreCase()` fix.

**Comment by pdowler** [comment]
Is mapping from s_region to footprint column a content specific thing? If so it does not belong in this library. The cadc-tap-server-oracle library should be handling oracle-specific wrangling only or it will not be re-usable for other content in an oracle database.

**Comment by at88mph** [comment]
Yes, it is specific to ALMA's Oracle instance.  Should we move this class to the `opencadc/alma` repository, or should this class be made more generic to where we can just pass in the specific columns to be replaced?
