### ISSUE TITLE
column case sensitivity on index creation

### ISSUE THREAD

**Issue by brianmajor** [opencadc/tap#91]
In youcat, if one tries to create an index on a column with the incorrect case it results in a null pointer exception.

TableUpdateRunner initially gets the column (description) through the table.  This succeeds because TableDescription.getColumn() uses equalsIgnoreCase().

This allows the index creation to proceed, only to fail later (line 235) where a case-sensitive query for the column is executed and returns null.

**Comment by pdowler** [comment]
Even though the PostgreSQL back end is not case sensitive, the other specs that talk about table and column names (eg TAP) explicitly say that clients must use the names exactly as provided in the tap_schema... so case sensitive. 

It's OK to use equalsIgnoreCase to make things work as long as it is thorough. The actual sequence should:

1. find the column in the TableDesc using equalsIgnoreCase
2. use the exact table name and column name (from TableDesc and ColumnDesc) in the create index statement (in case back end is case-sensitive)
3. find/update column as in #1

**Comment by brianmajor** [comment]
Okay.  Steps 1 and 2 you describe above were already the case.  I've made the change for 3 in this pull request.
